In [ ]:
n = 5
i = 0

while i < n:
    print(i)
    if i == 3:
        print("i=%d, n=%d"%(i,n))
        #break
    i += 1
else:
    print("ok")

0
1
2
3
i=3, n=5
4
ok


# List & Range

In [2]:
mylist = [1,2,4,7,0]
for i in mylist:
    print(i)

1
2
4
7
0


In [3]:
a = list(range(1,5))
a += list(range(5,10))
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [4]:
print([0]*3)

b = [(1,2)] *3
print(b)

c = [[]]*3
print(c)

print(id(c[0]))
print(id(c[1]))

d = [list() for i in range(3)]
print(d) #在不同ID
print(id(d[0]))
print(id(d[1]))


[0, 0, 0]
[(1, 2), (1, 2), (1, 2)]
[[], [], []]
2287855784392
2287855784392
[[], [], []]
2287855984776
2287855985096


In [5]:
x = []
for i in range(12):
    x.append([])
    for j in range(3):
        x[i].append(j)

print(x)
print('------------------')
x[0] = [100,200,300,400]
x[1] = [3,3,3,3]
print(x)
print(x[1])
print(x[0][2])

[[0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2]]
------------------
[[100, 200, 300, 400], [3, 3, 3, 3], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2]]
[3, 3, 3, 3]
300


In [6]:
# list, dict 內部只是reference某一個元素，而不是copy

a = [1,2,3]
mylist = []
print(id(a))
mylist.append(a)
a = [4,5,6]
print(id(a))
mylist.append(a)
print('mylist1----->', mylist)

mylist2 = []
for i in range(2):
    a[i] += 1
    mylist2.append(a)
    #print(id(a))
    print('mylist2----->', mylist2)
    
mylist3 = []
for i in range(2):
    b = [4,5,6] #reset b
    b[i] += 1
    #print(id(b))
    mylist3.append(b)
    print('mylist3----->', mylist3)

2287856011464
2287856011656
mylist1-----> [[1, 2, 3], [4, 5, 6]]
mylist2-----> [[5, 5, 6]]
mylist2-----> [[5, 6, 6], [5, 6, 6]]
mylist3-----> [[5, 5, 6]]
mylist3-----> [[5, 5, 6], [4, 6, 6]]


In [7]:
#多維陣列
mylist = []
w,h = 5,4

Matrix = [[0 for x in range(h)] for y in range(w)]
print(Matrix)

Matrix[0][1] = 4
mylist.append(Matrix)
print(mylist)
print(mylist[0])
print(mylist[0][0])
print(mylist[0][0][1])

for i in mylist:
    for j in i:
        for k in j:
            print(k)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[[[0, 4, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]]
[[0, 4, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[0, 4, 0, 0]
4
0
4
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


# Tuple Example

In [8]:
# for a,b var in 
x = [1,2,3,4]
y = [5,6,7,8]

for a,b,c in [(x,"Incremental PCA",100),(y,"PCA",200)]:
    print(a)
    print(b)
    print(c)
    
for a in [(x,"Incremental PCA",100),(y,"PCA",200)]:
    print(a)

[1, 2, 3, 4]
Incremental PCA
100
[5, 6, 7, 8]
PCA
200
([1, 2, 3, 4], 'Incremental PCA', 100)
([5, 6, 7, 8], 'PCA', 200)


# More on Data Structure: List Comprehension

In [9]:
vec = [[1,2,3],[4,5,6],[7,8,9]]
y = [num for elem in vec for num in elem ]
print(y)

combs = []
for elem in vec:
    for num in elem:
        combs.append(num)
print(combs)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [10]:
matrix = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]

print(matrix)

y = [[row[i] for row in matrix] for i in range(4)]
print(y)

print(*matrix) #脫離list
a = list(zip(*matrix)) #上下併並存在tuple
print(a)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]
[1, 2, 3, 4] [5, 6, 7, 8] [9, 10, 11, 12]
[(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]


# Dict Example

In [11]:
# dict comprehension

k = {x: x**2 for x in [1,2,3]}
print(k)

{1: 1, 2: 4, 3: 9}


In [12]:
mydict = {'A':100, 'B':1, 'C':1}
print(mydict)

# keys() values()
print(list(mydict.keys()))
print(list(mydict.values()))

# 'in' operator
print('D' in mydict)

if 'A' in mydict:
    print("Yes", mydict['A'])
else:
    print("No")
    
for i,k in enumerate(mydict): #denotes(index,key)
    print(i,k)
    
for k,v in mydict.items(): #denotes(key, value)
    print(k,v)

{'A': 100, 'B': 1, 'C': 1}
['A', 'B', 'C']
[100, 1, 1]
False
Yes 100
0 A
1 B
2 C
A 100
B 1
C 1


# Quiz_1

|      | 國文 | 英文 | 數學 |
|------|----- |-----|------|
| 小英 | 80   | 90  | 35   | 
| 小P  | 70   | 88  | 80   |
| 阿強 | 50   | 40  | 59   |

- 國文跟數學都及格的人?有多少人?
- 三科都及格的人?有多少人?
- 三個人的數學的平均分數?
- 三科平均分數大於70分的人有哪些人?

In [13]:
score = {'小英':[80,90,35],'小P':[70,88,80],'阿強':[50,40,59]}

In [14]:
# 國文跟數學都及格的人?有多少人?
print([name for name,points in score.items() if points[0]>60 and points[2]>60])
print(len([name for name,points in score.items() if points[0]>60 and points[2]>60]))        

['小P']
1


In [15]:
# 三科都及格的人?有多少人?
print([name for name,points in score.items() if points[0]>60 and points[1]>60 and points[2]>60])
print(len([name for name,points in score.items() if points[0]>60 and points[1]>60 and points[2]>60]))

['小P']
1


In [16]:
# 三個人的數學的平均分數
import statistics
statistics.mean([person_score[2] for person_score in score.values()])

58

In [17]:
# 三科平均分數大於70分的人有哪些人?
import statistics
[name for name,points in score.items() if statistics.mean(points) > 70]

['小P']

In [18]:
all_pass = []
pass_set = [set() for i in range(3)] #國,英,數
pass70 = []
math_avg = .0
avg = 0
math_sum = .0
for student in score:
    sum = .0
    for i in range(3):
        s = score[student][i]
        sum += s
        if s >= 60:
            pass_set[i].add(student)
        if i == 2: #math
            math_sum += s #數學的總成績
    avg=round(sum/len(score[student]),2)
    print('the avg of',student,' is ',avg)
    if avg > 70:
        pass70.append(student)

the avg of 小英  is  68.33
the avg of 小P  is  79.33
the avg of 阿強  is  49.67


In [19]:
print(pass_set[0]) #國文及格
print(pass_set[1]) #英文及格
print(pass_set[2]) #數學及格

{'小英', '小P'}
{'小英', '小P'}
{'小P'}


## 國文跟數學都及格的人?有多少人?

In [20]:
ans = pass_set[0] & pass_set[2]
print(ans)
print(len(ans))

{'小P'}
1


## 三科都及格的人?有多少人?

In [21]:
ans = pass_set[0] & pass_set[1] & pass_set[2]
print(ans)
print(len(ans))

{'小P'}
1


## 三個人的數學的平均分數?

In [22]:
print(round(math_sum / len(score), 2))

58.0


## 三科平均分數大於70分的人有哪些人?

In [23]:
print(pass70)

['小P']


# Function Call

In [24]:
# write Fibonacci series up to n
def fib(n):
    ''' Print a Fibonacci series up to n. '''
    a,b = 0,1
    while a < n:
        print(a, end=' ')
        a,b = b,a+b
    print()

fib(2000)

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 


In [25]:
# return Fibonacci series up to n
def fib2(n):
    result = []
    a,b = 0,1
    while a < n:
        result.append(a)
        a, b = b, a+b
    return result

x = fib2(100)
print(x)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


# Argument Passing

In [26]:
'''
Python的function是屬於call by assignment，由變數型態是mutable或immutable決定是call by value or call by reference
mutable belongs to call by reference ; immutable belongs to call by value. 
'''

'\nPython的function是屬於call by assignment，由變數型態是mutable或immutable決定是call by value or call by reference\nmutable belongs to call by reference ; immutable belongs to call by value. \n'

In [27]:
a = 100

def fun(a):
    a *= 2
    print(a)

fun(a)
print(a)

200
100


In [28]:
b = 'it'
def fun_str(s):
    s = "hello!"+s
    print(s)

fun_str(b)
print(b)

hello!it
it


In [29]:
# function example: List is called by reference
#parameter: list

def fun(a):
    a[0] = 100

mylist = [10,20,30]
fun(mylist)
print(mylist)

[100, 20, 30]


In [30]:
# function example: dict is called by reference
# parameter: dict

def fun1(a):
    a['a'] = a['a']*2
    
mydict = {'a':5, 'b':10}
fun1(mydict)
print(mydict)

{'a': 10, 'b': 10}


In [31]:
def square(a):
    return a**2

a = 10
print(a)
a = square(a)
print(a)

10
100


In [32]:
# function內宣布的object，也可以用return方式給函式外來使用
# 但呼叫function，其內部function宣告的object，每次都會產生新的。

def fun(a):
    data = [] #create a new list
    print(id(data))
    data.append(a)
    data.append(a+10)
    return data,a

c = 20
x,y = fun(c)
print(x)
print(y)
print(id(x))

print("---------")

c = 100
s,t = fun(c)
print(s)
print(t)
print(id(s))

2287856134408
[20, 30]
20
2287856134408
---------
2287855981768
[100, 110]
100
2287855981768


# Default Argument Values

In [33]:
def ask_ok(prompt, retries=2, remminder="Please try again!"):
    while True:
        ok = input(prompt)
        if ok in ('y','ye','yes'):
            return True
        if ok in ('n','no','nop','nope'):
            return False
        retries = retries - 1
        if retries < 0 :
            raise ValueError('invalid user response')
        print(remminder)

ask_ok('Do you really want to quit?')

Do you really want to quit?y


True

In [34]:
# The default values are evaluated at the point of function definition in the defining scope

i = 5
def f(arg=i):
    print(arg)

i = 6
f()

5


In [35]:
# The default value is evaluated only once
# This makes difference when the default is a mutable object such as list, dictionary, or instances of most classes.

def f1(a, L=[]):
    '''print(type(L),id(L))'''
    L.append(a)
    return L

list1 = f1(1)
print(list1, id(list1))
list2 = f1(2)
print(list2, id(list2))
list3 = f1(3)
print(list3, id(list3))

[1] 2287855738440
[1, 2] 2287855738440
[1, 2, 3] 2287855738440


In [36]:
def f2(a, L=None):
    '''print(type(L),id(L))'''
    if L == None:
        L = []
    L.append(a)
    return L

list1 = f2(1)
print(list1, id(list1))
list2 = f2(2)
print(list2, id(list2))
list3 = f2(3)
print(list3, id(list3))

[1] 2287855454664
[2] 2287856301320
[3] 2287856011912


In [37]:
#不定量參數寫法

def test(value, *arguments, **keywords):
    print(value)
    for arg in arguments:
        print(arg)
    print("-"*40)
    for kw in keywords:
        print(kw,":",keywords[kw])

test(10,20,30,a=100,b=200,c=300)

10
20
30
----------------------------------------
a : 100
b : 200
c : 300


In [38]:
def concat(*args, sep='/'):
    #print(args)
    return sep.join(args)

str1 = concat('earth','mars','venus','earth/mars/venus')
print(str1)
str2 = concat('earth','mars','venus','earth/mars/venus', sep=',')
print(str2)

earth/mars/venus/earth/mars/venus
earth,mars,venus,earth/mars/venus


In [39]:
args = [3,6]
print(*args)
print(list(range(*args)))

def test(**keywords):
    for kw in keywords:
        print(kw,":",keywords[kw])
        
test(a=100, b=200, c=300)

dict1 = {'a':100, 'b':200, 'c':300}
test(**dict1)

3 6
[3, 4, 5]
a : 100
b : 200
c : 300
a : 100
b : 200
c : 300


In [40]:
# global
x = 10

def myfun():
    global x
    x = 20
    print(x)

print(x)
myfun()
print(x)

10
20
20


In [41]:
def square():
    global a
    a = 5
    a = a**2
    return a

a = 10
print(a)
square()
print(a)

10
25


In [42]:
# global, 針對immutable，參數要加global，才能存取到外部variable，否則一律視為local

s = 'I love Paris!'

def f():
    global s
    s += "I love London!"
    
print(s)
f()
print(s)

I love Paris!
I love Paris!I love London!


In [43]:
# You can "access" non-local variable without sepcifically declare it,
# but you have to declare it to change it.

a = 5
b = 300

def myfun():
    b = 10
    print(a)
    print(b)

print(a)
print(b)
print('-'*10)
myfun()
print('-'*10)
a = 500
myfun()
print('-'*10)
print(a)
print(b)

5
300
----------
5
10
----------
500
10
----------
500
300


In [44]:
# Local Variable V.S. Global Variable
# Local 產生新的變數(label)

def foo(x,y):
    global a #代表外面的label
    a = 100
    x,y = y,x
    b = 200
    print("---",a,b,x,y)
    
a, b, x, y = 1, 2, 3, 4
print(a, b, x, y)
foo(x,y)
print(a, b, x, y)

1 2 3 4
--- 100 200 4 3
100 2 3 4


In [45]:
h = []
a = 10

def fun():
    h.append(a)
    
fun()
print(h)
fun()
print(h)

[10]
[10, 10]


In [46]:
# 全域變數 V.S. 區域變數

x1 = [2,4,6]
a = 5

def fun1():
    x1[1] = 100 #會更改
    print('-'*10)
    
def fun2():
    x1 = [1,2,3] #初值設定: x1是local
    print('-'*10)
    print(x1)
    
def fun3():
    a = 10 #初值設定: a是local
    print('-'*10)
    print(a)
    
def fun4():
    global a
    a = 1000 #初值設定為local，但global明確定義a是global
    print('-'*10)
    print(a)
    
def fun5():
    global x1 #改變外面的label，必須加入global，否則新的x1代表是該function內所定義
    x1 = [1, 2, 3] #初值設定: x1是local
    
def fun6():
    x1.append(8)
    print('-'*10)
    print(x1)
    

    
    
print(x1)
fun1()
print(x1)
fun2()
fun3()
fun4()
fun5()
fun6()

[2, 4, 6]
----------
[2, 100, 6]
----------
[1, 2, 3]
----------
10
----------
1000
----------
[1, 2, 3, 8]


# Nonlocal: 在函數或其它作用域中使用外層(非全域)變數
## nonlocal關鍵字用在函數或其它作用域中使用外層(非全域)變數

# Enclosing Functions
## Functions inside Functions

In [47]:
i = 1
def l1():
    i = 2
    def l2():
        print(i)
    l2()

l1()

2


In [48]:
def outer(a):
    
    def inner():
        nonlocal a
        a += 1
        print("inner a = ",a)
    
    a += 1
    inner()
    print("outer a = ",a)
    
a = 10
print('global a =',a)
outer(a)
print('global a =',a)

global a = 10
inner a =  12
outer a =  12
global a = 10


In [49]:
# lambda function
# Python提供了一個簡易的function define: lambda，用完即丟，不著痕跡。

def func(x,y,z):
    return x+y+z

print(func(1,2,3))

func2 = lambda x,y,z: x+y+z
print(func2(1,2,3))

6
6


# Lambda & Map Function

In [50]:
# map function 
# lambda 也可以應用在map上

my_list = [1,2,3]
ans = list(map(lambda i : i**2, my_list)) #需要轉成list，才能印出
print(ans) #[1, 4, 9]

a = [1,2,3,4]
b = [17,12,11,10]
c = [-1,-4,5,9]

# lambda 需要2個數兩個參數
print(list(map(lambda x,y: x+y, a,b))) #[18, 14, 14, 14]
# lambda 需要3個數兩個參數
print(list(map(lambda x,y,z: x+y+z, a,b,c))) #[18, 14, 14, 14]

[1, 4, 9]
[18, 14, 14, 14]
[17, 10, 19, 23]


# Zip & Enumerate Example

In [51]:
# Zip Example 1

A = list(range(5))
B = list(range(5,10))
Z = list(zip(A,B))
print(Z)

for i,j in Z:
    print(i,j)

[(0, 5), (1, 6), (2, 7), (3, 8), (4, 9)]
0 5
1 6
2 7
3 8
4 9


In [52]:
# enumerate
A = [1,2,3,4]
B = [5,6,7,8]

for i, v in enumerate(zip(A,B)):
    print(i,v[0],v[1])
    
emotions = ['Angry','Disgust','Fear','Happy','Sad','Surprise','Neutral']
for emotion_id, emotion_name in enumerate(emotions):
    print(emotion_id, emotion_name)

0 1 5
1 2 6
2 3 7
3 4 8
0 Angry
1 Disgust
2 Fear
3 Happy
4 Sad
5 Surprise
6 Neutral


In [53]:
for x in range(0,11):
    print('{0:-20d}{1:-20d}{2:-20d}'.format(x,x**2,x*x*x))

                   0                   0                   0
                   1                   1                   1
                   2                   4                   8
                   3                   9                  27
                   4                  16                  64
                   5                  25                 125
                   6                  36                 216
                   7                  49                 343
                   8                  64                 512
                   9                  81                 729
                  10                 100                1000


# File Processing: CSV, JSON, Pickle

In [54]:
# read text file ==> read()
#1. 讀取整個文檔，將文檔內容放到一個字符串變量中
#2. 如果文檔大於可用內存，不可能使用這種處理

f = open('Config.txt', 'r', encoding='utf-8')
print(f.read())
f.close()

a=5
b=4
c=3
d=2
f=1
e=0


In [55]:
# 路徑處理
import os.path
myfile = ['a.txt','b.csv','c.docx']
for filename in myfile:
    print(os.path.join(r'D:\Python_Summarize\Python_Training\ITtraining', filename))

D:\Python_Summarize\Python_Training\ITtraining\a.txt
D:\Python_Summarize\Python_Training\ITtraining\b.csv
D:\Python_Summarize\Python_Training\ITtraining\c.docx


In [56]:
# read txt file ==> readline()

f = open('Config.txt', 'r', encoding='utf-8')

for line in f:
    print(line)
    
f.close()

a=5

b=4

c=3

d=2

f=1

e=0


In [57]:
# read txt file ==> readline()
# 每次讀取一行，比readlines()慢得多

f = open('Config.txt', 'r', encoding='utf-8')
while True:
    line = f.readline()
    if line:
        print(line)
    else:
        break

f.close()

a=5

b=4

c=3

d=2

f=1

e=0


In [58]:
# read txt file ==> readlines()
#1. 一次性讀取整個文檔
#2. 自動將文檔內容分析成list

f = open('Config.txt', 'r', encoding='utf-8')
lines = f.readlines()
result = list()

for line in lines:
    print(line,end='\n')
    result.append(line.strip())
    
f.close()

print('-'*40)
print(result)

a=5

b=4

c=3

d=2

f=1

e=0
----------------------------------------
['a=5', 'b=4', 'c=3', 'd=2', 'f=1', 'e=0']


In [59]:
# Write txt File
#'r+' -> read + write text
#'w+' -> read + write text
#'a+' -> append + read text


result = ['a=5\n', 'b=4\n', 'c=3\n', 'd=2\n', 'f=1\n', 'e=0']

f = open('result_readlines.txt', 'w', encoding='utf-8')

for line in result:
    print(line,end='\n')
    f.write(line)
f.close()


a=5

b=4

c=3

d=2

f=1

e=0


In [60]:
# file I/O: try...except...
# 由於檔讀寫時都有可能產生IOError，一旦出錯，後面的f.close()就不會調用。所以為了保證無論是否出錯都能正確地關檔。
# 但 try...finally...每次都這麼寫實在太繁瑣，所以Python引入了with語句來自動幫我們調用close()方法

'''
try:
    f = open('Non-Exist-File.txt', 'r', encoding='utf-8')
    print(f.read())
finally:
    if f:
        f.close()
'''

try:
    with open('Non-Exist-File.txt', 'r', encoding='utf-8') as f:
        print(f.read())
except IOError:
    print('Error')
    
# f.close()
# print(f.read())


Error


In [61]:
try:
    f = open('result_readlines.txt', 'a+', encoding='utf-8')
    print('Ready to Read File')
    f.write('Hello')
except:
    print("Error")
finally:
    print('OK')

Ready to Read File
OK


# Getting File Using HTTPs (URLlib)

In [62]:
import sys
import urllib.request
import matplotlib.pyplot as plt

src_file = 'data1.csv'

try:
    data = open(src_file, 'r', ) #encoding='utf-8'
except IOError:
    print('No Such File and Try to Get File Using HTTP Get')
    urllib.request.urlretrieve('https://email.chcg.gov.tw/df/rqlhk4hoh92lfl1lz612l42genhoej/105%E5%B9%B4%E5%90%84%E5%8F%B01-12%E6%9C%88%E6%9C%88%E5%A0%B1(%E5%A4%96%E9%83%A8)e%E7%89%88.csv', src_file)
    data = open(src_file, 'r', ) #encoding='utf-8'
    
# data.close()

lines = []
DataSet = []

for line in data:
    print(line.strip().split(","))
    DataSet.append((line.strip().split(",")))

# print(DataSet)
print(DataSet[0][0])


['105年彰化縣政府各就業服台（第1季）績效表', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
['項目', '時間', '"求職人數']
['（新登記）"', '"求才人數']
['(新登記)"', '"求職推介']
['就業人數']
['（有效）"', '"求才僱用人']
['數（有效）"', '"推介人次']
['（有效）"', '諮詢人次', '', '', '"電訪']
['廠商數"', '實際拜訪廠商', '"開發']
['職缺數"', '"轉介']
['數"', '"申訴']
['數"', '追蹤輔導', '', '其它']
['站別', '', '', '', '', '', '', '法令', '職訓', '就服', '', '', '', '', '', '"追蹤']
['人次"', '"結案']
['人數"', '備註']
['勞工處就業服務台', '1月', '43', '307', '36', '42', '88', '2', '0', '292', '59', '0', '284', '0', '0', '84', '39', '0']
['', '2月', '33', '277', '19', '19', '56', '1', '2', '187', '45', '0', '277', '0', '0', '57', '19', '0']
['', '3月', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
['小計', '', '76', '584', '55', '61', '144', '3', '2', '479', '104', '0', '561', '0', '0', '141', '58', '0']
['全興就業服務台', '1月', '44', '385', '22', '21', '56', '2', '2', '206', '184', '0', '358', '0', '0', '60', '31', '0']
['', '2月', '33', '373', '15', '13', '53', '3', '1', '188', '54', 

In [63]:
# process csv file
import csv
filename = 'my_validate.csv'
text = open(filename, 'w+')
s = csv.writer(text, delimiter=',', lineterminator='\n')
s.writerow(['id','value'])
ans = [[1,100],[2,200],[3,300],[4,400],[5,500]]
for i in range(len(ans)):
    s.writerow(ans[i])
text.close()

In [64]:
# process JSON format file
import json

data = {
    'name':"Ace",
    'Shares':100,
    'price':542.23    
}

json_str = json.dumps(data)
print(json_str)

# Writing JSON Data
with open('data.json', 'w') as f:
    json.dump(data, f)
    
# Reading Data Back
with open('data.json', 'r') as f:
    data = json.load(f)

print(data)

{"name": "Ace", "Shares": 100, "price": 542.23}
{'name': 'Ace', 'Shares': 100, 'price': 542.23}


In [65]:
import pickle

# take user input to take the amount of data
number_of_data = 5
data = []

# take input of the data
for i in range(number_of_data):
    raw = i
    data.append(raw)
    
# open a file, where you can store the data
file = open('pickle', 'wb')

# dump information to that file
pickle.dump(data, file)

# close the file
file.close()

# Reading Back
file = open('pickle', 'rb')
data = pickle.load(file)
file.close()

print('Showing the Pickle Data: ')

cnt = 0
for item in data:
    print('The data {} is: {}'.format(cnt, item))
    cnt += 1


Showing the Pickle Data: 
The data 0 is: 0
The data 1 is: 1
The data 2 is: 2
The data 3 is: 3
The data 4 is: 4


In [66]:
'''
If you need to determine whether an exception was raised,
but do not intend to hand a simpler form of the raise statement,
allows you to re-raise the exception.
'''

while True:
    try:
        x = int(input('Pleas Enter a Number: '))
        break
    except ValueError:
        print('ValueError')
        print('Oops! This was no valid number. Try again...')
    except NameError:
        print('NameError')
        print('Oops! This was no valid number. Try again...')
    except:
        print('TryException')
        print('Oops! This was no valid number. Try again...')
    finally:
        print('Handling')

print(x)

Pleas Enter a Number: 5
Handling
5


In [67]:
try:
    raise NameError('NameError')
except:
    try:
        raise IOError('ValueError')
    except NameError:
        print('Except - NameError')
    except ValueError:
        print('Except - ValueError')
    except:
        print('An Exception Flew By')
finally:
    print('Finally')
    raise #re-raise the same exception

An Exception Flew By
Finally


RuntimeError: No active exception to reraise

In [ ]:
import sys

i = 0

try:
    f = open('Config.txt', 'r', encoding='utf-8')
    s = f.readline()
    print(s)
    
    i = 500
    i = int(i)
    # i = int(s.strip())
    # raise ValueError('manually raise the exception') #manually raise the exception

except OSError as ERR:
    print('OS Error: {0}'.format(ERR))
    
except ValueError as ERR:
    print('ValueError: {0}'.format(ERR))
    print('Could Not Convert Data to an Integer.')

except:
    print('Unexpected Error',sys.exc_info()[0])
    print(sys.exc_info())
    
else:
    print(i)
    f.close()

finally:
    print('Always Get in Here...Finally')

In [82]:
# write Fibonacci series up to n
def fib(n):
    ''' Print a Fibonacci series up to n. '''
    a,b = 0,1
    while a < n:
        print(a, end=' ')
        a,b = b,a+b
    print()

    
def main():
    a = fib(2000)
    print('test fib(2000)= {}'.format(a))
    
print(__name__)
    
if __name__ == '__main__':
    main()
    print(__name__)

__main__
0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 
test fib(2000)= None
__main__


In [2]:
class ClassName:
    def __init__(self, data2):
        # __init__ is the constructor
        self.dataMember1 = 'data1'
        self.dataMember2 = data2
    def printDataMember(self):
        print("DataMember1 is {}".format(self.dataMember1))
        print("DataMember2 is {}".format(self.dataMember2))
    def fun(self, arg1):
        self.printDataMember()
        print("arg1 is {}".format(arg1))
 
data2 = 'argument2'
object1 = ClassName(data2)
object1.printDataMember()
object1.fun('hello')


DataMember1 is data1
DataMember2 is argument2
DataMember1 is data1
DataMember2 is argument2
arg1 is hello


In [4]:
# class
class Myclass:
    '''
        This is my first class
    '''
    # class attribute ; class variable
    x = 0
    y = 0
    print('Myclass Created')
    def __init__(self, name):
        #print(self)
        self.name = name
        self.y = 100
        Myclass.x += 1
    
    def show(self):
        print(self.name)
        print(Myclass.x)
        print(self.y)
        print(Myclass.y)
        
a = Myclass("Tom")
a.show()
print(a.name)

b = Myclass("Joseph")
b.show()

c = Myclass("Ace")
c.show()

My = Myclass # set alternative class name
d = My("ITtraining")
d.show()

print(Myclass.x)

Myclass Created
Tom
1
100
0
Tom
Joseph
2
100
0
Ace
3
100
0
ITtraining
4
100
0
4


## class inheritance

In [5]:
# class inheritance
class MySubClass(Myclass):
    '''
    This is my first Subclass
    '''
    print('MySubClass Created')
    def __init__(self, name, height, weight):
        super().__init__(name) # super() to get the parent class
        self.height = height
        self.weight = weight
        
    def show(self): # overwirte the show() method in parent class
        print("name:{}".format(self.name))
        print("height:{}".format(self.height))
        print("weight:{}".format(self.weight))
        
    def BMI(self):
        return round(self.weight / ((self.height/100)**2),2)
    
MySub = MySubClass # set alternative class name
e = MySub("ITtraining",180,80)
e.show()
print(e.BMI())
        
f = MySub("Acer",200,80)
f.show()
print(f.BMI())

MySubClass Created
name:ITtraining
height:180
weight:80
24.69
name:Acer
height:200
weight:80
20.0


In [19]:
x = 100

class Demo:
    i = 10
    x += 2
    xx = x + 2
    print("xx={}".format(xx))

    def price(self):
        y = self.i * x #參考全域命名空間裡的物件x
        z = self.i * self.x #依實例屬性→類別屬性的順序來搜尋並參考
        # z = i * x #Error→在此無法看到資料i
        print("price y = %d"%y)
        print('Price z = %d'%z)
    
    def shop(self):
        self.price()
        Demo.i = 20
    
a = Demo()
b = Demo()
a.price()
a.shop()
print('(a.i, b.i) = ({},{})'.format(a.i, b.i))

a.i = 2 #設定實例屬性
Demo.i = 4 #變更類別屬性
print('(a.i, b.i) = ({},{})'.format(a.i, b.i))


xx=104
price y = 1000
Price z = 1020
price y = 1000
Price z = 1020
(a.i, b.i) = (20,20)
(a.i, b.i) = (2,4)


In [110]:
class Base():
    iii = 5

class Test(Base):
    def __init__(self):
        #self.iii = iii
        pass
    def test_print(self):
        print(self.iii)

Test = Test()
print(Test.test_print())

5
None


##  Private Attribute & Method

In [15]:
# Private Variable: __var
# Private Method: def __XXX(self, ...):
class Demo:
    __x = 0
    y = 50
    
    def __init__(self,i):
        self.j = 10
        self.__i = i
        Demo.__x += 1
    
    def getJ(self):
        return self.j
    
    def getI(self):
        return self.__i
    
    @classmethod
    def getX(cls):
        return cls.__x
    
    def __get(self): # private method
        return self.getJ(),self.getI()
    
    def get(self): # public method
        return self.__get()
    
a = Demo(1000)

# public instance variable
print("a.j={}".format(a.j))
print("a.getJ={}".format(a.getJ()))

# private instance variable
print("a.getI={}".format(a.getI()))

# public class variable
print("Demo.y={}".format(Demo.y))

# private class variable
print("Demo.x={}".format(Demo.getX()))

# private method
print("a(i,j)={}".format(a.get()))

a.j=10
a.getJ=10
a.getI=1000
Demo.y=50
Demo.x=1
a(i,j)=(10, 1000)


## @classmethod

In [2]:
class CoeffVar:
    coefficient = 10
    
    @classmethod #指定為類別方法
    def mul(cls, fact): #第一引數為cls
        return cls.coefficient * fact
    
#定義繼承類別CoeffVar的類別MulFive
class MulFive(CoeffVar):
    coefficient = 5
    
x = CoeffVar.mul(4)
print(x)

x = MulFive.mul(4)
print(x)

40
20


## @staticmethod

In [11]:
# class -> static method

class MySubClass2(MySubClass):
    '''
    This is my second Subclass
    '''
    def __init__(self, name, height, weight):
        super().__init__(name, height, weight) # super() to get the parent class
    
    def show(self):
        super().show() # call parent show()
        
    @staticmethod
    def bmi(h, w):
        return w / ((h/100)**2)

g = MySubClass2('AceHoDBS',175,75)
g.show()
bmi = MySubClass2.bmi(175, 73)
print(round(bmi,2))


name:AceHoDBS
height:175
weight:75
23.84


## Time

In [24]:
from datetime import datetime, date

def process_time(stime):
    #2021-04-11 15:22:42.635415
    time_slot = -1
    date1, time1 = stime.split(' ')
    date1 = [int(i) for i in date1.split('-')] #[2021, 4, 11] Y/M/D
    #print(date1)
    time1 = [float(i) for i in time1.split(':')] #[15.0, 22.0, 42.635415] H/M/S
    #print(time1)
    t = datetime(date1[0], date1[1], date1[2], int(time1[0]), int(time1[1])).time()
    print(t) #15:22:00
    
    #timeslot0 : 2017/08/14-01:00:00 ~ 2017/08/14-09:00:00
    t0 = t.replace(hour=1, minute=0)
    #print(t0)
    
    #timeslot1 : 2017/08/14-09:00:00 ~ 2017/08/14-17:00:00
    t1 = t.replace(hour=9, minute=0)
    #print(t1)
    
    #timeslot2 : 2017/08/14-17:00:00 ~ 2017/08/14-21:00:00
    t2 = t.replace(hour=17, minute=0)
    #print(t2)
    
    #timeslot3 : 2017/08/14-21:00:00 ~ 2017/08/15-01:00:00
    t3 = t.replace(hour=21, minute=0)
    #print(t3)
    
    #AM01:00~AM09:00
    if (t>=t0 and t<t1):
        time_slot = 0
        
    #AM09:00~PM17:00
    elif (t>=t1 and t<t2):
        time_slot = 1
    
    #PM17:00~PM21:00
    elif (t>=t2 and t<t3):
        time_slot = 2
    
    # > PM21:00
    else:
        time_slot = 3
     
    #weekday
    weekday = date(date1[0], date1[1], date1[2]).weekday() #Monday:0, Tuesday:1, ....,Sunday:6
    print(weekday)
    
    return weekday, time_slot
    
# stime = '2021-04-12 15:22:42.635415'
stime=str(datetime.now())
process_time(stime)

15:50:00
6


(6, 1)

In [3]:
print(datetime.now())

2021-04-11 15:22:42.635415


In [6]:
float(22)

22.0

In [2]:
int('04')

4

## Numpy

In [2]:
import numpy as np
np_array = np.array([[1,2,3],
                     [4,5,6]])
# Attribute of numpy.ndarray
type(np_array)
np_array.ndim # ndim: the number of axes (dimension) of the ndarray
np_array.shape # shape: the dimensions of the array, returns a tuple describing each dimension.
np_array.size # size: total elements in the ndarray
np_array.dtype #dtype: the data type of the elements in the ndarray. As ndarray is a homogeneous array, all elements in the ndarray should be the same type.
np_array.itemsize #itemsize: the size in byte of each element in the ndarray.

4

### 生成陣列

In [22]:
np.array((1,2,3,4,5,6)) #把Python tuple 轉換成陣列
np.array(range(10)) #把Python的range物件轉換成陣列
np.linspace(0,20,11) #生成等差陣列
np.logspace(0, 100, 10) #對數陣列

array([1.00000000e+000, 1.29154967e+011, 1.66810054e+022, 2.15443469e+033,
       2.78255940e+044, 3.59381366e+055, 4.64158883e+066, 5.99484250e+077,
       7.74263683e+088, 1.00000000e+100])

In [32]:
np.zeros((3,3)) #全0的3*3陣列
np.zeros((3,1)) #全0的3*1陣列
np.zeros((1,3)) #[0., 0., 0.]
np.zeros(3) #[0., 0., 0.]

np.ones((3,3)) #全1的3*3陣列

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.identity(3) #單位陣列
np.identity(2) 

array([[1., 0.],
       [0., 1.]])

In [46]:
np.empty((3,3)) #空陣列，只申請空間而不初始化，元素質是不確定的

array([[1.15875036e-311, 2.81617418e-322, 1.04082753e-047],
       [6.25549297e-091, 3.69852018e-033, 4.28951896e-038],
       [3.34880843e-061, 6.48224659e+170, 4.93432906e+257]])

### ndarray 與 數值 的運算

In [54]:
np_array = np.array([[1,2,3],
                     [4,5,6]])
np_array * 2
np_array / 3
np_array // 3
np_array ** 5
np_array + 10
np_array % 3

array([[1, 2, 0],
       [1, 2, 0]], dtype=int32)

In [58]:
np_array = np.array([[1,2,3],
                     [4,5,6]])

np_array  + np_array # 陣列之間的加法運算
np_array  * np_array # 陣列之間的乘法運算
np_array  - np_array # 陣列之間的減法運算
np_array  / np_array # 陣列之間的除法運算

array([[1., 1., 1.],
       [1., 1., 1.]])

In [65]:
a = np.array((1,2,3))
b = np.array(([1,2,3],[4,5,6],[7,8,9]))

c = a*b
print(c)

c/b
c/a

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

### ndarray轉置

In [67]:
b = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(b)
b.T #矩陣轉置

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [69]:
# 一維陣列轉置以後和原來是一樣的
a = np.array((1,2,3))
print(a)
a.T

[1 2 3]


array([1, 2, 3])

### ndarray 向量內積

In [71]:
a = np.array((5,6,7))
b = np.array((6,6,6))
a.dot(b) # 向量內積
np.dot(a,b) # 向量內積

108

### 陣列元素訪問

In [73]:
b = np.array(([1,2,3],[4,5,6],[7,8,9]))
b[0] #[1, 2, 3]
b[0][0] #1

1

### 陣列多元素同時訪問

In [85]:
x = np.arange(0,200,30,dtype=np.floating)
print(x)
x[[2,4,6]]

[  0.  30.  60.  90. 120. 150. 180.]


C:\Users\Ace\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  """Entry point for launching an IPython kernel.


array([ 60., 120., 180.])

In [91]:
a = np.random.randint(0,100,5) # 隨機整數值 (low, high, 數量)
print(a)

b = np.random.standard_normal(5) #常態分佈(高斯分布)，平均值µ = 0 ; 標準差σ = 1
print(b)

[97 43 89 46  7]
[ 1.97952235  0.89985011  1.27383044 -0.80575992 -0.52832787]


In [96]:
a = np.array(([1,2,3],[4,5,6],[7,8,9]))
np.sin(a) # 所有元素求正弦值
b = np.cos(a) # 所有元素求餘弦值
print(b)
np.round(b) # 四捨五入

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


array([[ 1., -0., -1.],
       [-1.,  0.,  1.],
       [ 1., -0., -1.]])

In [105]:
x = np.random.rand(5) # Random values in a given shape from a uniform distribution over [0,1]
print(x)
print(x*10)
np.floor(x*10) # 所有元素向下取最大整數
np.ceil(x*10) # 所有元素向上取最小整數

[0.59697951 0.82123897 0.48920611 0.02318243 0.37855078]
[5.96979506 8.21238969 4.89206115 0.23182431 3.78550775]


array([6., 9., 5., 1., 4.])

In [134]:
a = np.arange(0,20)
print(a) #一維陣列
b = a.reshape(4,5) # 改為4*5陣列
print(b)
np.sum(b) #所有元素求和
np.sum(b,axis=0) #縱向求和
np.sum(b,axis=1) #橫向求和
np.mean(b,axis=0) #縱向計算算術平均值
np.mean(b,axis=1) #橫向計算算術平均值
np.average(b,axis=0,weights=[0.3,0.1,0.5,0.1]) #縱向計算加權平均值
np.average(b,axis=1,weights=[0.2,0.3,0.1,0.4,0]) #橫向計算加權平均值

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([ 1.7,  6.7, 11.7, 16.7])

In [8]:
a = np.array(([1,12,3],[4,8,6],[2,5,9]))
np.max(a) #所有元素最大值
np.max(a,axis=0) #縱向求每列元素最大值
np.max(a,axis=1) #橫向求每行元素最大值

np.min(a) #所有元素最小值
np.min(a,axis=0) #縱向求每列元素最小值
np.min(a,axis=1) #橫向求每行元素最小值

array([1, 4, 2])

In [149]:
x = np.random.randint(0,15,size=(5,3)) #創建陣列
print(x)
np.std(x) #所有元素標準差
np.std(x,axis=0) #縱向求每列元素標準差
np.std(x,axis=1) #橫向求每行元素標準差

[[11  1  3]
 [11  7 14]
 [13  7  1]
 [ 0  6  4]
 [13  4  8]]


array([4.3204938 , 2.86744176, 4.89897949, 2.49443826, 3.68178701])

In [12]:
x = np.random.randint(0,15,size=(5,3)) #創建陣列
print(x)
np.var(x) #所有元素變異數
np.std(x,axis=0) #縱向求每列元素變異數
np.std(x,axis=1) #橫向求每行元素變異數

[[12  2  9]
 [10 11 10]
 [12  5  5]
 [ 6 13 12]
 [ 5  5 13]]


array([4.18993503, 0.47140452, 3.29983165, 3.09120617, 3.77123617])

In [17]:
x = np.random.randint(0,15,size=(5,3)) #創建陣列
print(x)

np.sort(x, axis=0) # 縱向排序
np.sort(x, axis=1) # 橫向排序


[[12  4  4]
 [13 13  3]
 [ 2 14  9]
 [ 7  1  3]
 [ 8  6 11]]


array([[ 4,  4, 12],
       [ 3, 13, 13],
       [ 2,  9, 14],
       [ 1,  3,  7],
       [ 6,  8, 11]])

In [35]:
a = np.arange(0,20,2) # step = 2
len(a)
a = a.reshape(2,5) # reshape() 方法返回新陣列
a = a.reshape(-1, 2) # reshape() 方法返回新陣列 ； -1 表示自動計算
a.shape = 2,5 #改為2行5列
a.shape = 10,-1 # -1 表示自動計算
a


array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18]])

### Numpy 切片操作

In [3]:
a = np.arange(0,21)
# a.shape = 2,-1 #改為2行5列
print(a)
a[1:5] # 前1:4個元素
a[:5] #前5個元素
a[::5] #隔n個取元素
a[::-1] #反向元素

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1,  0])

In [18]:
a = np.arange(1,26) # 創建陣列
# len(a)
a.shape = 5,-1 # 修改陣列大小
print(a)
a[0,2:5] # 第0行中下標[2:5]之間的元素值
a[1] #第1行所有元素
a[2:5,2:5] #行下標和列下標都介於[2:5]之間的元素值

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

### ndarray 布林運算

In [27]:
x = np.random.rand(20) #包含20個亂數的陣列
x.shape = 5,-1
print(x)
x>0.6 #比較陣列中每個元素值是否大於0.6
x[x>0.6] #獲取陣列中大於0.6的元素值

[[0.19401348 0.79020586 0.20931551 0.91637014]
 [0.12328192 0.92299284 0.0925292  0.01580323]
 [0.86618968 0.72532584 0.41802952 0.01882288]
 [0.72176446 0.59333424 0.32067894 0.79793741]
 [0.74146007 0.10624906 0.62122109 0.86839558]]


array([0.79020586, 0.91637014, 0.92299284, 0.86618968, 0.72532584,
       0.72176446, 0.79793741, 0.74146007, 0.62122109, 0.86839558])

In [47]:
a = np.random.randint(0,100,10) # 創建陣列
a.shape = 2,-1
print(a)

b = np.random.randint(0,100,10) # 創建陣列
b.shape = 2,-1
print(b)

a>b #兩個陣列中對應位置上的元素比較
a[a>b]
a[a==b]
a[a<b]

b[a>b]
b[a==b]
b[a<b]

[[11 70 39 46  1]
 [61 54 98 61 75]]
[[63 33 55 61 49]
 [75 79 71 78 90]]


array([63, 55, 61, 49, 75, 79, 78, 90])

### 只取小數

In [54]:
x = np.random.rand(5)*100
print(x)

#只取小數
x = [t-int(t) for t in x]
x

[19.58894618 89.33598003 51.48515223 95.95657695  5.07391138]


[0.5889461754522145,
 0.3359800320291839,
 0.4851522288875785,
 0.956576953001445,
 0.0739113801371083]

## ndarray.broadcast
### 將不同形狀的矩陣或是數組加減乘除

In [68]:
a = np.arange(0,10)
a = a.reshape(10,-1)
print(a)

b = np.arange(11,21)
b = b.reshape(-1,10)
print(b)

a + b
a - b
a*b
a/b

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[11 12 13 14 15 16 17 18 19 20]]


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667,
        0.0625    , 0.05882353, 0.05555556, 0.05263158, 0.05      ],
       [0.18181818, 0.16666667, 0.15384615, 0.14285714, 0.13333333,
        0.125     , 0.11764706, 0.11111111, 0.10526316, 0.1       ],
       [0.27272727, 0.25      , 0.23076923, 0.21428571, 0.2       ,
        0.1875    , 0.17647059, 0.16666667, 0.15789474, 0.15      ],
       [0.36363636, 0.33333333, 0.30769231, 0.28571429, 0.26666667,
        0.25      , 0.23529412, 0.22222222, 0.21052632, 0.2       ],
       [0.45454545, 0.41666667, 0.38461538, 0.35714286, 0.33333333,
        0.3125    , 0.29411765, 0.27777778, 0.26315789, 0.25      ],
       [0.54545455, 0.5       , 0.46153846, 0.42857143, 0.4       ,
        0.375     , 0.35294118, 0.33333333, 0.31578947, 0.3       ],
       [0.63636364, 0.58333333, 0.5384615

In [76]:
a = np.arange(0,10)
a.shape = -1,10
print(a)

b = np.arange(11,21)
b = b.reshape(10,-1)
print(b)

np.dot(a,b)

[[0 1 2 3 4 5 6 7 8 9]]
[[11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]


array([[780]])

### 分段函數

In [80]:
x = np.random.randint(0,200,20)
print(x)

np.where(x<50,0,1) #小於50的元素值對應0，其它對應1

np.piecewise(x, [x<40,x>70],[lambda x:x*2, lambda x:x*3]) #小於40的元素值乘以2，大於70的元素值乘以3，其它元素變為0

[  9  14 128  40 193  45  14   7  95 157  50  32  19 155  21  25  63  88
  55 126]


array([ 18,  28, 384,   0, 579,   0,  28,  14, 285, 471,   0,  64,  38,
       465,  42,  50,   0, 264,   0, 378])

### 計算唯一值以及出現次數

In [85]:
x = np.random.randint(0,100,20)
print(x)

np.bincount(x) #元素出現次數
np.sum(x) #所有元素之和
len(x)
np.unique(x) #返回唯一元素值

[24 72 64 69  2 92 62 21 70 60 86 48 49 86 28 70 30 21  0 57]


array([ 0,  2, 21, 24, 28, 30, 48, 49, 57, 60, 62, 64, 69, 70, 72, 86, 92])

### Numpy Matrix

In [95]:
a_list = [3, 5, 7]
a_mat = np.matrix(a_list) # 創建矩陣
print(a_mat)
a_mat.T #矩陣轉置
a_mat.shape #矩陣形狀
a_mat.size
a_mat*a_mat.T # 矩陣相乘
a_mat.mean() #元素平均值
a_mat.sum() #所有元素之和
a_mat.max()

[[3 5 7]]


7

In [106]:
# x = np.random.randint(0,50,9).reshape(3,3)
# print(x)

c_mat = np.matrix([[15, 19, 3], [18, 37, 23], [24, 18, 1]])  # 創建矩陣
print(c_mat)
c_mat.argsort(axis=0) #縱向排序後的元素序號
c_mat.argsort(axis=1) #橫向排序後的元素序號
c_mat.diagonal() #矩陣對角線元素
c_mat.flatten() # 矩陣平舖

[[15 19  3]
 [18 37 23]
 [24 18  1]]


matrix([[15, 19,  3, 18, 37, 23, 24, 18,  1]])

## Pandas Basic


In [5]:
import numpy as np
import pandas as pd

x = pd.Series([1, 3, 5, 7, np.nan], index=['A', 'B', 'C', 'D', 'E'])
print(x)
print(x.values)
print(x['B'])
print(x[1])

A    1.0
B    3.0
C    5.0
D    7.0
E    NaN
dtype: float64
[ 1.  3.  5.  7. nan]
3.0
3.0


In [7]:
x = pd.Series([1, 3, 5, 7, np.nan])
print(x[1])

3.0
